### ISSUE TITLE
dmvn() does not work with data matrices

### ISSUE THREAD

**Issue by torockel** [snoweye/EMCluster#11]
Hi everyone,

I wanted to use `dmvn()` with a data matrix. However, I was not able to do so:
``` r
library(EMCluster)
#> Loading required package: MASS
#> Loading required package: Matrix
p <- 2
x <- matrix(1:6, nrow = 3, ncol = p)
mu <- rep(1, p)
LTsigma <- c(1, 0, 1)
dmvn(x, mu, LTsigma)
#> Error in dlmvn(x, mu, LTsigma, log = log): Dimensions of x, mu or LTsigma do not agree!

length(x)
#> [1] 6
ncol(x)
#> [1] 2
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

From the docs: "x the data matrix, dimension n * p." So, I thought p must be the number of columns from x.  If I am correct, then this line https://github.com/snoweye/EMCluster/blob/ad654453067cfe50fb855ab22df56d99d718fa83/R/fcn_dlmvnorm.r#L198 should be `p <- ncol(x)` instead of `p <- length(x)`. However, I did not look at the code of the function to check, if `R_dlmvnorm` can handle a matrix or if x must be an atomic vector as maybe hinted here:
https://github.com/snoweye/EMCluster/blob/ad654453067cfe50fb855ab22df56d99d718fa83/R/fcn_dlmvnorm.r#L195

Sorry for bothering you again..

**Comment by snoweye** [comment]
[This](https://github.com/snoweye/EMCluster/commit/403126b09bd04489096c2dc6b02affe827b541ad) should fix the issue.

**Comment by torockel** [comment]
It is close, but it does not really fix the issue. A more realistic example:
``` r
library(EMCluster)
#> Loading required package: MASS
#> Loading required package: Matrix
dmvn(da2$da, da2$Mu[1, ], da2$LTSigma[1, ])
#> Error in dlmvn(x, mu, LTsigma, log = log): Dimensions of x, mu or LTsigma do not agree!
```

<sup>Created on 2022-02-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
I think `nrow(x)` should be changed to `ncol(x)` and ` my.dlmvnorm()` should be applied over rows instead of columns. I will do a small PR, so you can see the suggested changes more easily.

**Comment by snoweye** [comment]
Thanks. [This](https://github.com/snoweye/EMCluster/commit/c58224435143abb474d830dd8087a58687920d5a) should be fine.

`*.wt` function aims only for `t(x)` directly, e.g., `x<-t(da1$da); dmixmvn.wt(head(x), emobj)`, assuming `x` is very big, so it may save some time in this way.

**Comment by torockel** [comment]
Thank you for the fix and the explanation.
